version: '3'
services:
  document-propagation-server:
    image: cafebinario/document-propagation-server
    ports:
        - 8000:8000
    networks:
      - default
  document-propagation-example-hello:
    image: cafebinario/document-propagation-example-hello
    ports:
        - 8080:8080
    networks:
      - default
    depends_on:
      - document-propagation-server
  document-propagation-example-world:
    image: cafebinario/document-propagation-example-world
    ports:
        - 8090:8090
    networks:
      - default
    depends_on:
      - document-propagation-server